name: syzygy
description: 'Syzygy Flame game'
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
